name: Deploy Azure Function - serverlesscosmosdb

on:
  push:
    branches:
      - main  # Automatically deploy on push to main branch
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Adjust if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: "serverlesscosmosdb"  # Azure Function App Name
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}